In [ ]:
pip install gymnasium

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 953.9/953.9 kB 9.3 MB/s eta 0:00:00


In [ ]:
import gymnasium as gym
import numpy as np

In [ ]:
env=gym.make('FrozenLake-v1',desc=None,map_name="4x4",is_slippery=True,render_mode='rgb_array')
n_observations=env.observation_space.n
n_actions=env.action_space.n

In [ ]:
print("num of states",n_observations)
print("num of actions",n_actions)

num of states 16
num of actions 4


In [ ]:
Q_table=np.zeros((n_observations,n_actions))
Q_table

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
Q_table=np.zeros((n_observations,n_actions))
Q_table

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
Q_table[9,:]

array([0., 0., 0., 0.])

In [ ]:
n_episodes=10000
steps_allowed=100
epsilon=1
decay_rate=0.001
min_epsilon=0.01
max_epsilon=1
gamma=0.99
lr=0.1

In [ ]:
rewards_per_episodes=list()

In [ ]:
for e in range(n_episodes):
  #we initialize the first state of the episode
  state = env.reset()[0]
  done = False

  #sum the rewards that the agent gets from the environment
  total_reward = 0

  for i in range(steps_allowed):
    # epsilon greedy strategy
    # we initiate a random number between 0 and 1
    # if the random_number is less than the exploration proba(epsilon)
    #     the agent explores
    # else
    #     he exploits his knowledge

    if np.random.uniform(0,1) < epsilon:
        action = env.action_space.sample()
    else:
        action = np.argmax(Q_table[state,:])

    # The environment runs the chosen action and returns
    # the next state, a reward and true if the episode is ended.
    next_state, reward, done, truncated , info = env.step(action)

    # We update our Q-table using the Q-learning iteration
    Q_table[state, action] = (1-lr) * Q_table[state, action] \
                       + lr*(reward + gamma* np.max(Q_table[next_state,:]))
    total_reward = total_reward + reward

    state = next_state
    # If the episode is finished, we leave the for loop
    if done:
        break

  #We update the exploration proba using exponential decay formula
  epsilon = exploration_rate = min_epsilon + \
    (max_epsilon - min_epsilon) * np.exp(-decay_rate*e)
  rewards_per_episodes.append(total_reward)




In [ ]:
len(rewards_per_episodes)

10000

In [ ]:
rewards_per_thousand_episodes=np.split(np.array(rewards_per_episodes),n_episodes/1000)

In [ ]:
count=1000
print('----------Average reward per thousand episodes-------------')
for r in rewards_per_thousand_episodes:
  print(count,':',str(sum(r/1000)))
  count+=1000

----------Average reward per thousand episodes-------------
1000 : 0.04000000000000003
2000 : 0.20900000000000016
3000 : 0.43200000000000033
4000 : 0.5520000000000004
5000 : 0.6180000000000004
6000 : 0.6560000000000005
7000 : 0.6350000000000005
8000 : 0.6600000000000005
9000 : 0.7070000000000005
10000 : 0.6770000000000005


In [ ]:
print('--------------updated Q-Table-----------------')
print(Q_table)

--------------updated Q-Table-----------------
[[0.51957777 0.4656804  0.4721151  0.46469299]
 [0.34238096 0.38609447 0.20617913 0.44017707]
 [0.35631069 0.25791229 0.28994825 0.29597314]
 [0.04587922 0.14670675 0.06118677 0.08093614]
 [0.537507   0.44641284 0.40922397 0.40438832]
 [0.         0.         0.         0.        ]
 [0.2863711  0.1268666  0.14727624 0.0722539 ]
 [0.         0.         0.         0.        ]
 [0.45785883 0.43193889 0.30896736 0.56733977]
 [0.41949599 0.58884035 0.38467473 0.24093275]
 [0.58298853 0.38059189 0.35043147 0.27375777]
 [0.         0.         0.         0.        ]
 [0.         0.         0.         0.        ]
 [0.52763366 0.61057345 0.65844025 0.44909118]
 [0.75326954 0.87214575 0.75753517 0.73943925]
 [0.         0.         0.         0.        ]]


In [ ]:
import time
from IPython.display import clear_output

In [ ]:
%pip install gymnasium[classic_control] comet_ml
import comet_ml
comet_ml.init(project_name="frozen_lake")
env = gym.wrappers.RecordVideo(env, 'gameplay video')

In [ ]:
#Visualising the game
for episode in range(3):
  state=env.reset()[0]
  done=False
  print('----------EPISODE:',episode+1,'---------\n\n\n\n')
  time.sleep(1)

  for step in range(steps_allowed):
    clear_output(wait=True)
    print(env.render())
    time.sleep(0.4)

    action = np.argmax(Q_table[state,:])
    new_state, reward, done, truncated, info = env.step(action)

    if done:
      clear_output(wait=True)
      print(env.render())
      if reward == 1:
          print("****You reached the goal!****")
          time.sleep(3)
      else:
          print("****You fell through a hole!****")
          time.sleep(3)
      clear_output(wait=True)
      break

    state=new_state

env.close()

[[[180 200 230]
  [180 200 230]
  [180 200 230]
  ...
  [180 200 230]
  [180 200 230]
  [180 200 230]]

 [[180 200 230]
  [204 230 255]
  [204 230 255]
  ...
  [204 230 255]
  [204 230 255]
  [180 200 230]]

 [[180 200 230]
  [235 245 249]
  [204 230 255]
  ...
  [204 230 255]
  [204 230 255]
  [180 200 230]]

 ...

 [[180 200 230]
  [235 245 249]
  [235 245 249]
  ...
  [204 230 255]
  [235 245 249]
  [180 200 230]]

 [[180 200 230]
  [235 245 249]
  [235 245 249]
  ...
  [204 230 255]
  [204 230 255]
  [180 200 230]]

 [[180 200 230]
  [180 200 230]
  [180 200 230]
  ...
  [180 200 230]
  [180 200 230]
  [180 200 230]]]
****You reached the goal!****
